### ISSUE TITLE
Add support for arm64 in Docker image

### ISSUE THREAD

**Issue by GalacticLion7** [openbullet/OpenBullet2#131]
**Is your feature request related to a problem? Please describe.**
I can't run the `openbullet/openbullet2` image on my Raspberry Pi 4 because it only supports amd64.

**Describe the solution you'd like**
Add arm64 compatibility in the `openbullet/openbullet2` image.

**Describe alternatives you've considered**
I couldn't compile as directed in the forum page for the same reason.

**Comment by openbullet** [comment]
Done in https://github.com/openbullet/OpenBullet2/commit/9db9f8b6c1bc83d28682aee3f3d4f43b81adec59 you should be able to use the image on your rpi4 starting from update 0.1.7

**Comment by GalacticLion7** [comment]
I am still getting the same issue, even on 0.1.7:
```
ubuntu@ubuntu:~$ sudo docker run --name openbullet2 --rm -p 8069:5000 -v UserData:/app/UserData -it openbullet/openbullet2:latest
sudo: unable to resolve host ubuntu: Name or service not knownWARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
ubuntu@ubuntu:~$
```
It seems like `linux/arm64` is now supported, but not `linux/arm64/v8`.

**Comment by openbullet** [comment]
Alright thank you for the feedback, @meinname will take a look tomorrow

**Comment by meinname** [comment]
It seems docker has some problems to use the right architecture:
https://github.com/docker/for-linux/issues/1170#issuecomment-756845716

So let's approach it from both directions:
I set it now to explicitly to linux/arm64/v8 instead of just linux/arm64 and i moved the arm builds to top of the list https://github.com/openbullet/OpenBullet2/commit/e0261eb89c60017b1a279407601b85aef6252cf2
So hopefully on 1.1.8 it will be no problem anymore.

And in the meantime you can see if it is fixed with the latest docker version.

**Comment by openbullet** [comment]
@GalacticLion7 0.1.8 is live, please test
